name: 'Changelog Utils'
description: 'A collection of utilities for your changelog. Based on https://github.com/MalteHerrmann/changelog-utils'
author: 'Malte Herrmann'
inputs:
  command:
    description: 'Which changelog utility to use?'
    default: 'lint'
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
outputs:
  util-results:
    description: 'Changelog utility output'
runs:
  using: 'docker'
  image: 'Dockerfile'
