name: Changelog Linter

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  lint-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Run changelog linter
      uses: ./
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


