name: Changelog Linter

on:
  pull_request:

jobs:
  lint-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Run changelog linter
      # uses: MalteHerrmann/changelog-lint-action@135186f4c4e9d20424a5334c13ea749f601195b1
      uses: ./
      with:
          github_token: ${{ secrets.github_token }}


